name: Synchronize GraphQL Schema
on:
  # Every day at 11:15 AM (UTC)
  # NOTE: we do not use 0:00 UTC in order to avoid traffic spikes
  #       on GH's side caused by other cronjobs.
  schedule:
    - cron: "11 15 * * *"
  pull_request:
    paths:
      - .github/workflows/sync-gql-schema.yaml
  workflow_dispatch:

permissions: {}

jobs:
  download-schema:
    runs-on: ubuntu-24.04
    name: Download Schema

    permissions:
      contents: read

    outputs:
      files-changed: ${{ steps.detect-changes.outputs.files-changed }}
      schema-artifact-id: ${{ steps.upload-schema.outputs.artifact-id }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            pnpm-workspace.yaml
            bin/
          persist-credentials: false

      - name: Install pnpm
        run: |
          cd ./bin
          corepack enable
          corepack install

      - name: Install Dependencies
        run: |
          cd ./bin
          pnpm install --frozen-lockfile

      - name: Download
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir src/ # will write schema into it
          node ./bin/download-schema.js

      - name: Detect Changes
        id: detect-changes
        run: |
          files_changed=$(git status --porcelain | wc -l)

          if [[ "$files_changed" -gt 1 ]]; then
            echo "Detected $files_changed files changed, but only expected 1" >&2
            exit 1
          else
            # Will be 0 when not changed, and 1 when changed
            echo "files-changed=$files_changed" >> "$GITHUB_OUTPUT"
          fi

      - if: ${{ steps.detect-changes.outputs.files-changed > 0 }}
        name: Upload Schema
        id: upload-schema
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "New Schema"
          path: ./src/schema.graphql

  open-pr:
    runs-on: ubuntu-24.04
    name: Open Pull Request
    needs: [download-schema]

    # Only runs if there is a file to commit
    if: ${{ needs.download-schema.outputs.files-changed > 0 }}

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          artifact-ids: ${{ needs.download-schema.outputs.schema-artifact-id }}
          path: ${{ runner.temp }}/schema/

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true # needed to be able to push

      - name: Copy Schema
        env:
          RUNNER_TEMP: ${{ runner.temp }}
        run: |
          cp "$RUNNER_TEMP"/schema/schema.graphql ./src/schema.graphql

      # NOTE: we do not update existing PRs in case we may end up editing a malicious one
      - name: Close Existing PR (If Any)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |

          branch=bump-schema

          if ! git ls-remote --exit-code --heads origin "$branch"; then
            echo "OK: branch doesn't exist yet" >&2
            exit 0
          fi

          echo "Deleting existing PR..." >&2
          gh pr close \
            --comment "This pull request is outdated, closing it in favor of a newer one." \
            --delete-branch \
            "$branch"

      - name: Push Branch
        id: push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          title="Synchronize GitHub schema ($(date '+%Y-%m-%d'))"
          echo "title=$title" >> "$GITHUB_OUTPUT"

          git add src/schema.graphql
          git commit -m "$title

          Fetched around $(date)"
          git checkout -b bump-schema
          git push --set-upstream origin bump-schema

      - name: Open PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_TITLE: ${{ steps.push.outputs.title }}
        run: |
          gh pr create \
            --title "$PR_TITLE" \
            --body '<!-- PR by sync-gql-schema.yaml -->'
